
import { AppData, Member, Transaction, MzungukoItem } from './types';

export const DEMO_MEMBERS: Member[] = [
  { id: '1', name: 'Fatuma Hassan', role: 'Mwenyekiti', phone: '+255 712 111 111', paid: true, pass: '1234', isAdmin: true, contributions: 350000 },
  { id: '2', name: 'Amina Juma', role: 'Mhazini', phone: '+255 712 222 222', paid: true, pass: '1234', isAdmin: false, contributions: 350000 },
  { id: '3', name: 'Rehema Mwamba', role: 'Katibu', phone: '+255 712 333 333', paid: true, pass: '1234', isAdmin: false, contributions: 350000 },
  { id: '4', name: 'Zainab Omar', role: 'Mwanachama', phone: '+255 712 444 444', paid: true, pass: '1234', isAdmin: false, contributions: 150000 },
  { id: '5', name: 'Hadija Salim', role: 'Mwanachama', phone: '+255 712 555 555', paid: false, pass: '1234', isAdmin: false, contributions: 50000 },
  { id: '6', name: 'Maryam Abdalla', role: 'Mwanachama', phone: '+255 712 666 666', paid: false, pass: '1234', isAdmin: false, contributions: 50000 },
];

export const DEMO_HISTORIA: Transaction[] = [
  { id: 'h1', memberId: '1', memberName: 'Fatuma Hassan', type: 'Mchango', amount: 50000, date: '2024-01-10', notes: 'Jan mchango' },
  { id: 'h2', memberId: '2', memberName: 'Amina Juma', type: 'Mchango', amount: 50000, date: '2024-01-10', notes: 'Jan mchango' },
  { id: 'h3', memberId: '3', memberName: 'Rehema Mwamba', type: 'Mchango', amount: 50000, date: '2024-01-05', notes: 'Jan mchango' },
  { id: 'h4', memberId: '3', memberName: 'Rehema Mwamba', type: 'Malipo', amount: 300000, date: '2024-01-15', notes: 'Mzunguko #1' },
  { id: 'h5', memberId: '1', memberName: 'Fatuma Hassan', type: 'Mchango', amount: 50000, date: '2024-02-10', notes: 'Feb mchango' },
  { id: 'h6', memberId: '2', memberName: 'Amina Juma', type: 'Mchango', amount: 50000, date: '2024-02-10', notes: 'Feb mchango' },
  { id: 'h7', memberId: '3', memberName: 'Rehema Mwamba', type: 'Mchango', amount: 50000, date: '2024-02-05', notes: 'Feb mchango' },
  { id: 'h8', memberId: '2', memberName: 'Amina Juma', type: 'Malipo', amount: 300000, date: '2024-02-15', notes: 'Mzunguko #2' },
  { id: 'h9', memberId: '1', memberName: 'Fatuma Hassan', type: 'Mchango', amount: 50000, date: '2024-03-10', notes: 'Mar mchango' },
  { id: 'h10', memberId: '4', memberName: 'Zainab Omar', type: 'Mchango', amount: 50000, date: '2024-03-10', notes: 'Mar mchango' },
  { id: 'h11', memberId: '5', memberName: 'Hadija Salim', type: 'Mchango', amount: 50000, date: '2024-03-10', notes: 'Mar mchango' },
];

export const DEMO_MZUNGUKO: MzungukoItem[] = [
  { id: 'm1', memberId: '3', name: 'Rehema', month: 'January', status: 'done', position: 1 },
  { id: 'm2', memberId: '2', name: 'Amina', month: 'February', status: 'done', position: 2 },
  { id: 'm3', memberId: '1', name: 'Fatuma', month: 'March', status: 'current', position: 3 },
  { id: 'm4', memberId: '4', name: 'Zainab', month: 'April', status: 'waiting', position: 4 },
  { id: 'm5', memberId: '5', name: 'Hadija', month: 'May', status: 'waiting', position: 5 },
  { id: 'm6', memberId: '6', name: 'Maryam', month: 'June', status: 'waiting', position: 6 },
];

export const DEMO_SETTINGS = {
  groupName: "Vikoba cha Upendo",
  amount: 50000,
  payDay: 10
};

export const T = {
  sw: {
    dashboard: "Dashboard",
    members: "Wanachama",
    rotation: "Mzunguko",
    history: "Historia",
    reports: "Taarifa",
    whatsapp: "WhatsApp",
    settings: "Mipangilio",
    logout: "Ondoka",
    totalSavings: "Jumla ya Akiba",
    memberCount: "Wanachama",
    rotationProgress: "Maendeleo ya Mzunguko",
    paidToday: "Waliolipa",
    reminder: "Kumbusho",
    pendingPayment: "Wanachama ambao hawajalipa mwezi huu",
    sendWhatsapp: "Tuma Kumbusho",
    successMsg: "Wanachama wote wameshalipa!",
    recentTransactions: "Miamala ya Karibuni",
    addMember: "Ongeza Mwanachama",
    memberList: "Orodha ya Wanachama",
    rotationGrid: "Ratiba ya Mzunguko",
    receivingNow: "Mpokeaji wa Mwezi Huu",
    month: "Mwezi",
    amount: "Kiasi",
    status: "Hali",
    rules: "Sheria za VICOBA",
    rule1: "1. Kila mwanachama lazima alipe TZS 50,000 kila tarehe 10.",
    rule2: "2. Mzunguko hufanyika mara moja kila mwezi.",
    rule3: "3. Adhabu ya kuchelewa kulipa ni TZS 5,000.",
    rule4: "4. Mwanachama anaejitoa atarudishiwa akiba yake pungufu ya 10%.",
    type: "Aina",
    date: "Tarehe",
    notes: "Maelezo",
    makeContribution: "Weka Mchango",
    monthlyContributions: "Michango ya Kila Mwezi",
    contributionsByMember: "Michango kwa kila Mwanachama",
    savingsGrowth: "Kukua kwa Akiba",
    downloadPdf: "Pakua PDF",
    messageType: "Aina ya Ujumbe",
    preview: "Hakiki",
    send: "Tuma",
    groupSettings: "Mipangilio ya Kikundi",
    dataManagement: "Usimamizi wa Data",
    saveSettings: "Hifadhi Mipangilio",
    exportData: "Hamisha Data (JSON)",
    deleteAll: "Futa Data Zote",
    username: "Jina la Mtumiaji",
    password: "Neno la Siri",
    login: "Ingia",
    loginHint: "Fatuma/1234 (admin), Amina/1234 (mwanachama)",
    paid: "Alilipa",
    pending: "Hajalipa",
    phone: "Namba ya Simu",
    contribution: "Mchango",
    payout: "Malipo",
    now: "Sasa Hivi",
    received: "Amepokea",
    waiting: "Anasubiri",
    uploadPhoto: "Pakia Picha",
    removePhoto: "Ondoa Picha",
    memberName: "Jina la Mwanachama",
    loginPassword: "Neno la Siri la Kuingia",
    removeMember: "Muondoe Mwanachama",
    confirmRemove: "Je, una uhakika unataka kumuondoa mwanachama huyu?",
  },
  en: {
    dashboard: "Dashboard",
    members: "Members",
    rotation: "Rotation",
    history: "Payment History",
    reports: "Reports",
    whatsapp: "WhatsApp",
    settings: "Settings",
    logout: "Logout",
    totalSavings: "Total Savings",
    memberCount: "Members",
    rotationProgress: "Rotation Progress",
    paidToday: "Paid",
    reminder: "Reminder",
    pendingPayment: "Members who haven't paid this month",
    sendWhatsapp: "Send Reminder",
    successMsg: "All members have paid!",
    recentTransactions: "Recent Transactions",
    addMember: "Add Member",
    memberList: "Member List",
    rotationGrid: "Rotation Grid",
    receivingNow: "Current Receiver",
    month: "Month",
    amount: "Amount",
    status: "Status",
    rules: "VICOBA Rules",
    rule1: "1. Each member must pay TZS 50,000 every 10th day.",
    rule2: "2. Rotation occurs once every month.",
    rule3: "3. Penalty for late payment is TZS 5,000.",
    rule4: "4. A member who leaves will get 90% of their savings back.",
    type: "Type",
    date: "Date",
    notes: "Notes",
    makeContribution: "Record Contribution",
    monthlyContributions: "Monthly Contributions",
    contributionsByMember: "Contributions by Member",
    savingsGrowth: "Savings Growth",
    downloadPdf: "Download PDF",
    messageType: "Message Type",
    preview: "Preview",
    send: "Send",
    groupSettings: "Group Settings",
    dataManagement: "Data Management",
    saveSettings: "Save Settings",
    exportData: "Export Data (JSON)",
    deleteAll: "Delete All Data",
    username: "Username",
    password: "Password",
    login: "Login",
    loginHint: "Fatuma/1234 (admin), Amina/1234 (member)",
    paid: "Paid",
    pending: "Pending",
    phone: "Phone Number",
    contribution: "Contribution",
    payout: "Payment",
    now: "Current",
    received: "Received",
    waiting: "Waiting",
    uploadPhoto: "Upload Photo",
    removePhoto: "Remove Photo",
    memberName: "Member Name",
    loginPassword: "Login Password",
    removeMember: "Remove Member",
    confirmRemove: "Are you sure you want to remove this member?",
  }
};
